languageCode = 'zh-cn'
title = 'wakuwaku'
theme = 'diary'

defaultContentLanguage="zh"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    tabWidth = 4

# theme config

[params]
enableReadingTime=true

[[menu.main]]
url = "/posts"
name = "归档"
weight = 1
[[menu.main]]
url = "/categories"
name = "分类"
weight = 2
[[menu.main]]
url = "/tags"
name = "标签"
weight = 3
[[menu.main]]
url = "/index.xml"
name = "RSS"
weight = 4